name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Create Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: wangyoucao577/go-release-action@v1.24
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19
          binary_name: "go-chat"
          extra_files: LICENSE README.md
          executable_compression: "upx --best --lzma"
          ldflags: "-s -w -X main.version=${{ github.ref }} -X main.commit=${{ github.sha }}"
